spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

server:
  port: 8079

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/