spring:
  application:
    name: ai-service
  datasource:
    mongodb:
      uri: mongodb://localhost:27017/fitness_recommendation
      database: fitness_recommendation
  devtools:
    restart:
      log-condition-evaluation-delta: false

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



