spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config


server:
  port: 8001


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/